sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:GhCzs3W4Gj7eaQ2pLNwIWVCa
mono: none
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
before_script:
  - npm install -g @angular-devkit/build-angular
  - npm install -g @angular/cli
  - npm install

script:
  - ng build
  - ng test --watch=false